baseURL = "/"
languageCode = "en-us"
title = "Aidan Law - Healthcare IT Consultant"
description = "Healthcare IT Infrastructure Consultant specializing in legacy system modernization, HIPAA compliance, and custom solutions for medical practices."
pluralizelisttitles = false

theme = "poison"
[markup.goldmark.renderer]
	unsafe = true

[params]
	brand = "Aidan Law"
 	description = "Healthcare IT Infrastructure Consultant specializing in legacy system modernization, HIPAA compliance, and custom solutions for medical practices."
	menu = [
		{Name = "Services", URL = "/services/", HasChildren = false},
		{Name = "About", URL = "/about/", HasChildren = false},
		{Name = "Case Studies", URL = "/case-studies/", HasChildren = false},
		{Name = "Insights", URL = "/posts/", HasChildren = false},
		{Name = "Contact", URL = "/contact/", HasChildren = false},
	]

	favicon = "/images/favicon.webp" 

	rss_icon = true
	# Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
	rss_section = "posts"
	brand_image = "/images/profile.webp"
	github_url = "https://github.com/AidanFLaw"
	email_url = "mailto:contact@aidanlaw.xyz"
	resume = "/resume.pdf"

	linkedin_url = "https://www.linkedin.com/in/aidan-law-xyz/"
	# Healthcare teal/blue color scheme
	sidebar_bg_color = "#1E3A8A"
	sidebar_img_border_color = "#008B8B"
	sidebar_p_color = "#E0F2F1"
	sidebar_h1_color = "#FFF"
	sidebar_a_color = "#B2DFDB"
	sidebar_socials_color = "#FFF"

	# light mode - healthcare professional theme
	text_color = "#1A202C"
	content_bg_color = "#FAFAFA"
	post_title_color = "#1E3A8A"
	list_color = "#4A5568"
	link_color = "#008B8B"
	date_color = "#718096"
	table_border_color = "#E2E8F0"
	table_stripe_color = "#F7FAFC"

	# dark mode - healthcare professional theme
	text_color_dark = "#F7FAFC"
	content_bg_color_dark = "#1A202C"
	post_title_color_dark = "#B2DFDB"
	list_color_dark = "#A0AEC0"
	link_color_dark = "#4FD1C7"
	date_color_dark = "#A0AEC0"
	table_border_color_dark = "#2D3748"
	table_stripe_color_dark = "#2A4365"
	code_color = "#93032E"
	code_background_color = "#E5E5E5"
	code_color_dark = "#D9ABA0"
	code_background_color_dark = "#393D47"

	og_image = "/images/favicon.webp"
	publisher_icon = "/images/favicon.webp"  
[params.meta]
	favicon = false
	keywords = ["healthcare IT consultant", "HIPAA compliance", "legacy system modernization", "medical practice IT support", "healthcare cybersecurity", "EHR optimization", "Florida healthcare IT", "clinical workflow automation", "healthcare technology consultant", "medical IT infrastructure"]
	author = "Aidan Law"
	robots = "index, follow"

[taxonomies]
	series = 'series'
	tags = 'tags'